# Generated by Django 5.2.5 on 2025-11-11 11:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество')),
                ('reason', models.TextField(verbose_name='Причина брака')),
                ('status', models.CharField(choices=[('reported', 'Сообщено'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='reported', max_length=20, verbose_name='Статус')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сообщения')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
            ],
            options={
                'verbose_name': 'Бракованный товар',
                'verbose_name_plural': 'Бракованные товары',
                'db_table': 'defective_products',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expense_type', models.CharField(choices=[('physical', 'Физические'), ('overhead', 'Накладные')], max_length=20)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, choices=[('piece', 'Штука'), ('kg', 'Килограмм'), ('gram', 'Грамм')], max_length=10, null=True)),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('suzerain', 'Сюзерен'), ('vassal', 'Вассал'), ('civilian', 'Обыватель')], default='civilian', max_length=20)),
                ('state', models.CharField(choices=[('mechanical', 'Механическое'), ('automatic', 'Автоматическое')], default='automatic', max_length=20)),
                ('apply_type', models.CharField(choices=[('regular', 'Обычный'), ('universal', 'Универсальный')], default='regular', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MechanicalExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mechanical_expense_entries',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_weight_based', models.BooleanField(default=False, help_text='Продаётся на вес с шагом 0.1кг (минимум 1кг)', verbose_name='Весовой товар')),
                ('unit', models.CharField(choices=[('kg', 'Килограмм'), ('piece', 'Штука'), ('liter', 'Литр'), ('pack', 'Упаковка')], default='piece', max_length=10, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу')),
                ('price_per_100g', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Автоматически рассчитывается для весовых товаров', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за 100г')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Себестоимость')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductExpenseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proportion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_expense_relations',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('position', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'db_table': 'product_images',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suzerain_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ingredient_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_items',
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StoreProductCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField(default=0, verbose_name='Всего куплено')),
                ('product_count', models.IntegerField(default=0, verbose_name='Куплено этого товара')),
                ('last_bonus_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний бонус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Счётчик товаров магазина',
                'verbose_name_plural': 'Счётчики товаров магазинов',
                'db_table': 'store_product_counters',
            },
        ),
        migrations.CreateModel(
            name='BonusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество бонусных единиц')),
                ('bonus_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Стоимость бонуса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='orders.storeorder', verbose_name='Заказ')),
                ('partner', models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'История бонусов',
                'verbose_name_plural': 'История бонусов',
                'db_table': 'bonus_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
