# Generated by Django 5.2.5 on 2025-09-08 01:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus_every_n',
            field=models.PositiveIntegerField(default=21, verbose_name='Каждый N-й бесплатно'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_manufactured',
            field=models.BooleanField(default=False, help_text='Товар производится из других товаров/расходов', verbose_name='Производимый товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время производства (мин)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bonus_eligible',
            field=models.BooleanField(default=True, verbose_name='Участвует в бонусах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_order_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Минимум к заказу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена (шт/кг)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основное'),
        ),
        migrations.CreateModel(
            name='ProductionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество по умолчанию')),
                ('use_suzerain_input', models.BooleanField(default=False, verbose_name='Использовать ввод через Сюзерена')),
                ('default_suzerain_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество Сюзерена по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_templates', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Шаблон производства',
                'verbose_name_plural': 'Шаблоны производства',
                'db_table': 'production_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_unit', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Количество на единицу')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_used_in', to='products.product', verbose_name='Ингредиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_bom_items', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ингредиент продукта (устар.)',
                'verbose_name_plural': 'Ингредиенты продуктов (устар.)',
                'db_table': 'product_bom',
                'unique_together': {('product', 'ingredient')},
            },
        ),
    ]
