# Generated by Django 5.2.5 on 2025-11-14 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='defectiveproduct',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defective_products', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='defectiveproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='mechanicalexpenseentry',
            name='expense',
            field=models.ForeignKey(blank=True, limit_choices_to={'state': 'mechanical'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.expense'),
        ),
        migrations.AddField(
            model_name='mechanicalexpenseentry',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mechanical_expenses', to='products.productionrecord'),
        ),
        migrations.AddField(
            model_name='productexpenserelation',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_relations', to='products.expense'),
        ),
        migrations.AddField(
            model_name='productexpenserelation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_relations', to='products.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productionitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productionitem',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productionrecord'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeproductcounter',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_counters', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='storeproductcounter',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_counters', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='storeproductcounter',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_counters', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterUniqueTogether(
            name='mechanicalexpenseentry',
            unique_together={('record', 'expense')},
        ),
        migrations.AlterUniqueTogether(
            name='productexpenserelation',
            unique_together={('product', 'expense')},
        ),
        migrations.AlterUniqueTogether(
            name='productionitem',
            unique_together={('record', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productionrecord',
            unique_together={('partner', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='storeproductcounter',
            unique_together={('store', 'partner', 'product')},
        ),
    ]
