# Generated by Django 5.2.5 on 2025-10-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='partner',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='partner',
        ),
    ]
