# Generated by Django 5.2.5 on 2025-11-19 01:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_productcategory_bonushistory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity_weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Чем выше — тем больше накладных расходов несёт товар (по продажам за 90 дней)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Коэффициент популярности'),
        ),
    ]
