# Generated by Django 5.2.5 on 2025-10-16 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_expense_partner_alter_product_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonushistory',
            options={'ordering': ['-date'], 'verbose_name': 'История бонусов', 'verbose_name_plural': 'История бонусов'},
        ),
        migrations.AlterModelOptions(
            name='defectiveproduct',
            options={'ordering': ['-date'], 'verbose_name': 'Бракованный товар', 'verbose_name_plural': 'Бракованные товары'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at'], 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='mechanicalexpenseentry',
            options={'verbose_name': 'Механический расход', 'verbose_name_plural': 'Механические расходы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productexpenserelation',
            options={'verbose_name': 'Связь товар-расход', 'verbose_name_plural': 'Связи товар-расход'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterModelOptions(
            name='productionitem',
            options={'verbose_name': 'Строка производства', 'verbose_name_plural': 'Строки производства'},
        ),
        migrations.AlterModelOptions(
            name='productionrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Запись производства', 'verbose_name_plural': 'Записи производства'},
        ),
        migrations.AlterModelOptions(
            name='storeproductcounter',
            options={'verbose_name': 'Счётчик бонусов', 'verbose_name_plural': 'Счётчики бонусов'},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='calculated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Себестоимость (расчётная)'),
        ),
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Наценка %'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Рекомендуемая цена'),
        ),
        migrations.AddField(
            model_name='storeproductcounter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='bonus_count',
            field=models.IntegerField(default=0, verbose_name='Количество бонусов'),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма убытка'),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='apply_type',
            field=models.CharField(choices=[('regular', 'Обычный'), ('universal', 'Универсальный')], default='regular', max_length=20, verbose_name='Тип применения'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('physical', 'Физические'), ('overhead', 'Накладные')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма в месяц'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='state',
            field=models.CharField(choices=[('mechanical', 'Механическое'), ('automatic', 'Автоматическое')], default='automatic', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('suzerain', 'Сюзерен'), ('vassal', 'Вассал'), ('civilian', 'Обыватель')], default='civilian', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='unit',
            field=models.CharField(blank=True, choices=[('piece', 'Штука'), ('kg', 'Килограмм'), ('gram', 'Грамм')], max_length=10, null=True, verbose_name='Единица'),
        ),
        migrations.AlterField(
            model_name='mechanicalexpenseentry',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Потрачено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('piece', 'Штучный'), ('weight', 'Весовой')], default='piece', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bonus',
            field=models.BooleanField(default=False, verbose_name='Участвует в бонусах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suzerain_expense',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'suzerain'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suzerain_products', to='products.expense', verbose_name='Расход-Сюзерен'),
        ),
        migrations.AlterField(
            model_name='productexpenserelation',
            name='proportion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Пропорция'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='ingredient_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость ингредиентов'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чистая прибыль'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Накладные расходы'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='quantity_produced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доход'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='suzerain_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Объём Сюзерена (кг)'),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общие расходы'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='storeproductcounter',
            name='bonus_eligible_count',
            field=models.IntegerField(default=0, verbose_name='Счётчик до бонуса'),
        ),
        migrations.AlterField(
            model_name='storeproductcounter',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_counters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storeproductcounter',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='Всего куплено'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='position',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
