# Generated by Django 5.2.5 on 2025-10-31 09:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_bonushistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonushistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='defectiveproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mechanicalexpenseentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productexpenserelation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='productionitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productionrecord',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='storeproductcounter',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='storeproductcounter',
            name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='bonus_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='products.product'),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='apply_type',
            field=models.CharField(choices=[('regular', 'Обычный'), ('universal', 'Универсальный')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('physical', 'Физические'), ('overhead', 'Накладные')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='state',
            field=models.CharField(choices=[('mechanical', 'Механическое'), ('automatic', 'Автоматическое')], default='automatic', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('suzerain', 'Сюзерен'), ('vassal', 'Вассал'), ('civilian', 'Обыватель')], default='civilian', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='unit',
            field=models.CharField(blank=True, choices=[('piece', 'Штука'), ('kg', 'Килограмм'), ('gram', 'Грамм')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mechanicalexpenseentry',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('piece', 'Штучный'), ('weight', 'Весовой')], default='piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='suzerain_expense',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'suzerain'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suzerain_products', to='products.expense'),
        ),
        migrations.AlterField(
            model_name='productexpenserelation',
            name='proportion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='ingredient_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='quantity_produced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='suzerain_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='storeproductcounter',
            name='bonus_eligible_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeproductcounter',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_counters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storeproductcounter',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='product',
            name='calculated_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='markup_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recommended_price',
        ),
    ]
