# Generated by Django 5.2.5 on 2025-11-06 08:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_partnerorder_storeorder_storeorderitem_and_more'),
        ('products', '0004_alter_bonushistory_options_and_more'),
        ('stores', '0006_partnerinventory_returnrequest_returnrequestitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bonushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История бонусов', 'verbose_name_plural': 'История бонусов'},
        ),
        migrations.AlterModelOptions(
            name='defectiveproduct',
            options={'ordering': ['-reported_at'], 'verbose_name': 'Бракованный товар', 'verbose_name_plural': 'Бракованные товары'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterModelOptions(
            name='storeproductcounter',
            options={'verbose_name': 'Счётчик товаров магазина', 'verbose_name_plural': 'Счётчики товаров магазинов'},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bonushistory',
            name='bonus_count',
        ),
        migrations.RemoveField(
            model_name='bonushistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='defectiveproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='defectiveproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='defectiveproduct',
            name='date',
        ),
        migrations.RemoveField(
            model_name='storeproductcounter',
            name='bonus_eligible_count',
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='bonus_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Стоимость бонуса'),
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='orders.storeorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество бонусных единиц'),
        ),
        migrations.AddField(
            model_name='defectiveproduct',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата сообщения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defectiveproduct',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата решения'),
        ),
        migrations.AddField(
            model_name='defectiveproduct',
            name='status',
            field=models.CharField(choices=[('reported', 'Сообщено'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='reported', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Себестоимость'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен для заказа'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_weight_based',
            field=models.BooleanField(default=False, help_text='Продаётся на вес с шагом 0.1кг (минимум 1кг)', verbose_name='Весовой товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_100g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Автоматически рассчитывается для весовых товаров', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за 100г'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Килограмм'), ('piece', 'Штука'), ('liter', 'Литр'), ('pack', 'Упаковка')], default='piece', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='storeproductcounter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeproductcounter',
            name='last_bonus_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний бонус'),
        ),
        migrations.AddField(
            model_name='storeproductcounter',
            name='product_count',
            field=models.IntegerField(default=0, verbose_name='Куплено этого товара'),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='defective_products', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='reason',
            field=models.TextField(verbose_name='Причина брака'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='storeproductcounter',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_counters', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='storeproductcounter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_counters', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='storeproductcounter',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_counters', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='storeproductcounter',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='Всего куплено'),
        ),
        migrations.AlterField(
            model_name='storeproductcounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddIndex(
            model_name='bonushistory',
            index=models.Index(fields=['store', 'partner'], name='bonus_histo_store_i_9fefd3_idx'),
        ),
        migrations.AddIndex(
            model_name='bonushistory',
            index=models.Index(fields=['created_at'], name='bonus_histo_created_8f9c58_idx'),
        ),
        migrations.AddIndex(
            model_name='defectiveproduct',
            index=models.Index(fields=['partner', 'status'], name='defective_p_partner_f8b3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductcounter',
            index=models.Index(fields=['store', 'partner'], name='store_produ_store_i_f31633_idx'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_available'], name='products_is_acti_706d22_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_4083ff_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_bonus',
        ),
        migrations.RemoveField(
            model_name='product',
            name='position',
        ),
        migrations.RemoveField(
            model_name='product',
            name='suzerain_expense',
        ),
    ]
