# Generated by Django 5.2.5 on 2025-11-11 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='orderreturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='orderreturnitem',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderreturn', verbose_name='Возврат'),
        ),
        migrations.AddField(
            model_name='partnerorder',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_orders', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='partnerorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.partnerorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='partnerorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders_as_partner', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='store_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.storerequest', verbose_name='Запрос магазина'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.storeorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.storeorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['order_type', 'order_id'], name='order_histo_order_t_31ed9c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['created_at'], name='order_histo_created_1432ca_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorder',
            index=models.Index(fields=['partner', 'created_at'], name='partner_ord_partner_6b5a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorder',
            index=models.Index(fields=['status'], name='partner_ord_status_868ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorder',
            index=models.Index(fields=['idempotency_key'], name='partner_ord_idempot_3681e9_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['store', 'created_at'], name='store_order_store_i_8d9fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['partner', 'created_at'], name='store_order_partner_b476fc_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['is_fulfilled'], name='store_order_is_fulf_f5fe89_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['idempotency_key'], name='store_order_idempot_7a8c07_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['order', 'status'], name='order_retur_order_i_ecb35d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['idempotency_key'], name='order_retur_idempot_82f41a_idx'),
        ),
    ]
