# Generated by Django 5.2.5 on 2025-10-28 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_orderitem_uniq_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ключ идемпотентности'),
        ),
    ]
