# Generated by Django 5.2.5 on 2025-11-15 11:39

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0002_delete_productcategory_bonushistory_product_and_more'),
        ('stores', '0002_remove_storerequest_store_reque_store_i_b6d370_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'История заказов', 'verbose_name_plural': 'Истории заказов'},
        ),
        migrations.RemoveIndex(
            model_name='orderhistory',
            name='order_histo_order_t_31ed9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderhistory',
            name='order_histo_created_1432ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnerorder',
            name='partner_ord_partner_6b5a0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnerorder',
            name='partner_ord_status_868ecd_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeorder',
            name='store_order_store_i_8d9fdb_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeorder',
            name='store_order_partner_b476fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeorder',
            name='store_order_is_fulf_f5fe89_idx',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='type',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='is_fulfilled',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='store_request',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='bonus_items',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Бонусы (JSON)'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='defective_items',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Бракованные товары (JSON)'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='items_json',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Список товаров (JSON)'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='summary_json',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Сводка (JSON)'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='total_items_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее кол-во шт'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Общий вес (кг)'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='bonus_items',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Бонусные позиции (JSON)'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Оплата (опционально)'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='status',
            field=models.CharField(default='confirmed', editable=False, max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='summary_json',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Сводка (JSON)'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='total_items_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее кол-во шт'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Общий вес (кг)'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='partnerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='partnerorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='bonus_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма бонуса'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая сумма (без бонуса)'),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='is_bonus',
            field=models.BooleanField(default=False, verbose_name='Бонус?'),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerorderitem',
            unique_together={('order', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='storeorderitem',
            unique_together={('order', 'product')},
        ),
        migrations.AddIndex(
            model_name='partnerorder',
            index=models.Index(fields=['partner', 'status'], name='partner_ord_partner_8631f8_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['store', 'partner'], name='store_order_store_i_658360_idx'),
        ),
    ]
