# Generated by Django 5.2.5 on 2025-11-17 20:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderhistory_options_and_more'),
        ('products', '0002_delete_productcategory_bonushistory_product_and_more'),
        ('stores', '0002_remove_storerequest_store_reque_store_i_b6d370_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История заказа', 'verbose_name_plural': 'История заказов'},
        ),
        migrations.RemoveIndex(
            model_name='partnerorder',
            name='partner_ord_partner_8631f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeorder',
            name='store_order_store_i_658360_idx',
        ),
        migrations.AlterUniqueTogether(
            name='partnerorderitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='storeorderitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='bonus_items',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='defective_items',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='store',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='summary_json',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='total_items_qty',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='total_weight',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='bonus_items',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='summary_json',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='total_items_qty',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='total_weight',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID заказа'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_type',
            field=models.CharField(choices=[('partner', 'Заказ партнёра'), ('store', 'Заказ магазина')], max_length=20, null=True, verbose_name='Тип заказа'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='type',
            field=models.CharField(choices=[('general', 'Общий'), ('bonus', 'Бонус'), ('defect', 'Брак'), ('sold', 'Проданный'), ('returned', 'Возвращенный')], max_length=20, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='is_fulfilled',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='store_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.storerequest', verbose_name='Запрос магазина'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='partnerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('processing', 'Обработка'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='partnerorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='bonus_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Применён бонус'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders_as_partner', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='is_bonus',
            field=models.BooleanField(default=False, verbose_name='Бонусная позиция'),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['order_type', 'order_id'], name='order_histo_order_t_31ed9c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['created_at'], name='order_histo_created_1432ca_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorder',
            index=models.Index(fields=['partner', 'created_at'], name='partner_ord_partner_6b5a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorder',
            index=models.Index(fields=['status'], name='partner_ord_status_868ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['store', 'created_at'], name='store_order_store_i_8d9fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['partner', 'created_at'], name='store_order_partner_b476fc_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['is_fulfilled'], name='store_order_is_fulf_f5fe89_idx'),
        ),
    ]
