# Generated by Django 5.2.5 on 2025-11-06 08:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_idempotency_key'),
        ('products', '0004_alter_bonushistory_options_and_more'),
        ('stores', '0006_partnerinventory_returnrequest_returnrequestitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('processing', 'Обработка'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая сумма')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключ идемпотентности')),
            ],
            options={
                'verbose_name': 'Заказ партнёра',
                'verbose_name_plural': 'Заказы партнёров',
                'db_table': 'partner_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fulfilled', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая сумма')),
                ('bonus_applied', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Применён бонус')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключ идемпотентности')),
            ],
            options={
                'verbose_name': 'Заказ магазина',
                'verbose_name_plural': 'Заказы магазинов',
                'db_table': 'store_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу')),
                ('is_bonus', models.BooleanField(default=False, verbose_name='Бонусная позиция')),
            ],
            options={
                'verbose_name': 'Позиция заказа магазина',
                'verbose_name_plural': 'Позиции заказов магазинов',
                'db_table': 'store_order_items',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='orderreturn',
            options={'ordering': ['-created_at'], 'verbose_name': 'Возврат товаров', 'verbose_name_plural': 'Возвраты товаров'},
        ),
        migrations.AlterModelOptions(
            name='partnerorderitem',
            options={'verbose_name': 'Позиция заказа партнёра', 'verbose_name_plural': 'Позиции заказов партнёров'},
        ),
        migrations.RemoveConstraint(
            model_name='partnerorderitem',
            name='uniq_order_product',
        ),
        migrations.RenameField(
            model_name='orderreturnitem',
            old_name='return_order',
            new_name='return_request',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_id',
            field=models.PositiveIntegerField(default=django.utils.timezone.now, verbose_name='ID заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_type',
            field=models.CharField(choices=[('partner', 'Заказ партнёра'), ('store', 'Заказ магазина')], default=django.utils.timezone.now, max_length=20, verbose_name='Тип заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='reason',
            field=models.TextField(verbose_name='Причина возврата'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма возврата'),
        ),
        migrations.AlterField(
            model_name='orderreturnitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['order_type', 'order_id'], name='order_histo_order_t_31ed9c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['created_at'], name='order_histo_created_1432ca_idx'),
        ),
        migrations.AlterModelTable(
            name='partnerorderitem',
            table='partner_order_items',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='PartnerOrderItem',
        ),
        migrations.AddField(
            model_name='partnerorder',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_orders', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='partnerorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.partnerorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders_as_partner', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='store_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.storerequest', verbose_name='Запрос магазина'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.storeorder', verbose_name='Заказ'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['order', 'status'], name='order_retur_order_i_ecb35d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['idempotency_key'], name='order_retur_idempot_82f41a_idx'),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.storeorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddIndex(
            model_name='partnerorder',
            index=models.Index(fields=['partner', 'created_at'], name='partner_ord_partner_6b5a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorder',
            index=models.Index(fields=['status'], name='partner_ord_status_868ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerorder',
            index=models.Index(fields=['idempotency_key'], name='partner_ord_idempot_3681e9_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['store', 'created_at'], name='store_order_store_i_8d9fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['partner', 'created_at'], name='store_order_partner_b476fc_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['is_fulfilled'], name='store_order_is_fulf_f5fe89_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['idempotency_key'], name='store_order_idempot_7a8c07_idx'),
        ),
    ]
