# Generated by Django 5.2.5 on 2025-11-17 21:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderhistory_options_and_more'),
        ('products', '0002_delete_productcategory_bonushistory_product_and_more'),
        ('stores', '0002_remove_storerequest_store_reque_store_i_b6d370_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreturn',
            options={'ordering': ['-created_at'], 'verbose_name': 'Возврат по заказу', 'verbose_name_plural': 'Возвраты по заказам'},
        ),
        migrations.AlterModelOptions(
            name='orderreturnitem',
            options={'verbose_name': 'Позиция возврата по заказу', 'verbose_name_plural': 'Позиции возвратов по заказам'},
        ),
        migrations.RemoveIndex(
            model_name='orderreturn',
            name='order_retur_order_i_ecb35d_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderreturn',
            name='order_retur_idempot_82f41a_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnerorder',
            name='partner_ord_idempot_3681e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeorder',
            name='store_order_idempot_7a8c07_idx',
        ),
        migrations.RemoveIndex(
            model_name='storeorder',
            name='store_order_is_fulf_f5fe89_idx',
        ),
        migrations.RenameField(
            model_name='orderreturnitem',
            old_name='return_request',
            new_name='order_return',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='note',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='type',
        ),
        migrations.RemoveField(
            model_name='partnerorder',
            name='note',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='bonus_applied',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='is_fulfilled',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='note',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='new_status',
            field=models.CharField(max_length=16, null=True, verbose_name='Новый статус'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=16, verbose_name='Старый статус'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_returns', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_returns', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_returns', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='orderreturnitem',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина по позиции'),
        ),
        migrations.AddField(
            model_name='orderreturnitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='partnerorder',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='partnerorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AddField(
            model_name='partnerorderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_orders', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма в долг'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='storeorderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_id',
            field=models.PositiveIntegerField(verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_type',
            field=models.CharField(choices=[('partner', 'Заказ партнёра'), ('store', 'Заказ магазина'), ('return', 'Возврат по заказу')], max_length=16, null=True, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_entries', to='products.product', verbose_name='Товар (опционально)'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Idempotency key'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='orders.storeorder', verbose_name='Заказ магазина'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('cancelled', 'Отменён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма возврата'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='orderreturnitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderreturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_return_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderreturnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='partnerorder',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Для защиты от повторной отправки заказа с фронта', max_length=64, null=True, unique=True, verbose_name='Idempotency key'),
        ),
        migrations.AlterField(
            model_name='partnerorder',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_orders', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='partnerorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='partnerorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='partnerorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='partnerorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='partnerorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_order_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='partnerorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Idempotency key'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_orders', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='store_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders', to='stores.storerequest', verbose_name='Заявка магазина'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_order_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Количество'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['store', 'created_at'], name='order_retur_store_i_4f7b49_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['partner', 'created_at'], name='order_retur_partner_03ba9e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['status'], name='order_retur_status_be8450_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['status'], name='store_order_status_1814f8_idx'),
        ),
    ]
