# Generated by Django 5.2.5 on 2025-11-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_partnerorder_storeorder_storeorderitem_and_more'),
        ('stores', '0007_remove_region_code_remove_storerequest_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
