# Generated by Django 5.2.5 on 2025-09-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('response_template', models.TextField(blank=True, verbose_name='Шаблон ответа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория поддержки',
                'verbose_name_plural': 'Категории поддержки',
                'db_table': 'support_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('category', models.CharField(choices=[('technical', 'Техническая проблема'), ('billing', 'Вопросы по оплате'), ('account', 'Проблемы с аккаунтом'), ('order', 'Вопросы по заказам'), ('general', 'Общие вопросы'), ('feature', 'Запрос функций'), ('bug', 'Сообщение об ошибке')], default='general', max_length=20, verbose_name='Категория')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('closed', 'Закрыта')], default='open', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решена')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/', verbose_name='Вложение')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
            ],
            options={
                'verbose_name': 'Заявка поддержки',
                'verbose_name_plural': 'Заявки поддержки',
                'db_table': 'support_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Внутреннее сообщение')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_responses/', verbose_name='Вложение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Ответ поддержки',
                'verbose_name_plural': 'Ответы поддержки',
                'db_table': 'support_responses',
                'ordering': ['created_at'],
            },
        ),
    ]
