services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-me}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-}
    volumes:
      - ./data:/app/data
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    restart: unless-stopped