version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: baielapp_2
      POSTGRES_USER: baeil_app
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - baiel_network

  # Redis для кеша и Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - baiel_network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Django приложение
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=django-secret-key-baielapp-2025
      - DATABASE_URL=postgres://baeil_app:12345678@db:5432/baielapp_2
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: unless-stopped
    networks:
      - baiel_network

  # Celery worker
  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=False
      - SECRET_KEY=django-secret-key-baielapp-2025
      - DATABASE_URL=postgres://baeil_app:12345678@db:5432/baielapp_2
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: unless-stopped
    networks:
      - baiel_network

  # Celery beat (планировщик задач)
  celery-beat:
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=False
      - SECRET_KEY=django-secret-key-baielapp-2025
      - DATABASE_URL=postgres://baeil_app:12345678@db:5432/baielapp_2
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: unless-stopped
    networks:
      - baiel_network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  baiel_network:
    driver: bridge