# Generated by Django 5.2.5 on 2025-09-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('room_type', models.CharField(choices=[('private', 'Приватный чат'), ('support', 'Поддержка'), ('group', 'Групповой чат')], default='private', max_length=20, verbose_name='Тип комнаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Комната чата',
                'verbose_name_plural': 'Комнаты чата',
                'db_table': 'chat_rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('file', 'Файл'), ('system', 'Системное')], default='text', max_length=20, verbose_name='Тип сообщения')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Отметка о прочтении',
                'verbose_name_plural': 'Отметки о прочтении',
                'db_table': 'message_reads',
            },
        ),
    ]
