# Generated by Django 5.2.5 on 2025-09-10 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_alter_productimage_options_productimage_created_at_and_more'),
        ('stores', '0002_alter_storeinventory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('description', models.TextField(verbose_name='Описание')),
                ('every_nth_free', models.PositiveIntegerField(default=21, verbose_name='Каждый N-й товар бесплатно')),
                ('applies_to_all_products', models.BooleanField(default=True, verbose_name='Применяется ко всем товарам')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('products', models.ManyToManyField(blank=True, help_text='Если не выбрано - применяется ко всем', to='products.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Правило бонусов',
                'verbose_name_plural': 'Правила бонусов',
                'db_table': 'bonus_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BonusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_quantity', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Купленное количество')),
                ('bonus_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Бонусное количество')),
                ('cumulative_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Накопленное количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('bonus_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Размер скидки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='orders.order', verbose_name='Заказ')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='orders.orderitem', verbose_name='Позиция заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'История бонусов',
                'verbose_name_plural': 'История бонусов',
                'db_table': 'bonus_history',
                'ordering': ['-created_at'],
                'unique_together': {('order_item',)},
            },
        ),
    ]
