# Generated by Django 5.2.5 on 2025-08-30 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название правила')),
                ('description', models.TextField(verbose_name='Описание')),
                ('bonus_threshold', models.PositiveIntegerField(default=21, verbose_name='Каждый N-й товар бесплатно')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('applies_to_partners', models.BooleanField(default=True, verbose_name='Применяется к партнерам')),
                ('applies_to_stores', models.BooleanField(default=True, verbose_name='Применяется к магазинам')),
                ('valid_from', models.DateTimeField(verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Правило бонусной системы',
                'verbose_name_plural': 'Правила бонусной системы',
                'db_table': 'bonus_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items_ordered', models.PositiveIntegerField(default=0, verbose_name='Всего заказано товаров')),
                ('bonus_items_received', models.PositiveIntegerField(default=0, verbose_name='Получено бонусных товаров')),
                ('current_count', models.PositiveIntegerField(default=0, verbose_name='Текущий счет')),
                ('next_bonus_at', models.PositiveIntegerField(default=21, verbose_name='Следующий бонус на')),
                ('last_bonus_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего бонуса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_counter', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Счетчик бонусов',
                'verbose_name_plural': 'Счетчики бонусов',
                'db_table': 'bonus_counters',
            },
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Заработан'), ('used', 'Использован'), ('expired', 'Истек'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товаров')),
                ('amount_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сэкономленная сумма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to='stores.store')),
            ],
            options={
                'verbose_name': 'Бонусная операция',
                'verbose_name_plural': 'Бонусные операции',
                'db_table': 'bonus_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(verbose_name='Конец периода')),
                ('total_bonus_items', models.PositiveIntegerField(default=0, verbose_name='Всего бонусных товаров')),
                ('total_bonus_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая стоимость бонусов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_stats', to='stores.store')),
            ],
            options={
                'verbose_name': 'Статистика бонусов',
                'verbose_name_plural': 'Статистика бонусов',
                'db_table': 'bonus_statistics',
                'ordering': ['-period_start'],
                'unique_together': {('store', 'partner', 'period_start', 'period_end')},
            },
        ),
    ]
