# Generated by Django 5.2.5 on 2025-09-11 20:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points_earned', models.PositiveIntegerField(default=0, verbose_name='Всего очков заработано')),
                ('total_points_used', models.PositiveIntegerField(default=0, verbose_name='Всего очков потрачено')),
                ('current_points', models.PositiveIntegerField(default=0, verbose_name='Текущие очки')),
                ('total_items_purchased', models.PositiveIntegerField(default=0, verbose_name='Всего товаров куплено')),
                ('total_bonus_items_received', models.PositiveIntegerField(default=0, verbose_name='Всего бонусных товаров получено')),
                ('total_amount_saved', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Всего сэкономлено')),
                ('last_bonus_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего бонуса')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_balance', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Баланс бонусов',
                'verbose_name_plural': 'Балансы бонусов',
                'db_table': 'bonus_balances',
            },
        ),
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('description', models.TextField(verbose_name='Описание')),
                ('every_nth_free', models.PositiveIntegerField(default=21, verbose_name='Каждый N-й товар бесплатно')),
                ('bonus_type', models.CharField(choices=[('nth_free', 'Каждый N-й товар бесплатно'), ('percentage', 'Процентная скидка'), ('fixed_amount', 'Фиксированная сумма'), ('points', 'Бонусные очки')], default='nth_free', max_length=20, verbose_name='Тип бонуса')),
                ('percentage_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Процент скидки')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Фиксированная сумма')),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Множитель очков')),
                ('applies_to_all_products', models.BooleanField(default=True, verbose_name='Применяется ко всем товарам')),
                ('applies_to_all_stores', models.BooleanField(default=True, verbose_name='Применяется ко всем магазинам')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Минимальная сумма заказа')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Максимальная сумма скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('max_uses_per_store', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум использований на магазин')),
                ('max_uses_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум использований всего')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет (больше = выше)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('categories', models.ManyToManyField(blank=True, to='products.category', verbose_name='Категории')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('products', models.ManyToManyField(blank=True, help_text='Если не выбрано - применяется ко всем', to='products.product', verbose_name='Товары')),
                ('stores', models.ManyToManyField(blank=True, to='stores.store', verbose_name='Магазины')),
            ],
            options={
                'verbose_name': 'Правило бонусов',
                'verbose_name_plural': 'Правила бонусов',
                'db_table': 'bonus_rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BonusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items_purchased', models.PositiveIntegerField(verbose_name='Всего товаров куплено')),
                ('bonus_items', models.PositiveIntegerField(default=0, verbose_name='Бонусных товаров получено')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Очков заработано')),
                ('points_used', models.PositiveIntegerField(default=0, verbose_name='Очков потрачено')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='stores.store', verbose_name='Магазин')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonuses.bonusrule', verbose_name='Правило бонуса')),
            ],
            options={
                'verbose_name': 'История бонусов',
                'verbose_name_plural': 'История бонусов',
                'db_table': 'bonus_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusRuleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
                ('total_discount_given', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма скидок')),
                ('total_bonus_items_given', models.PositiveIntegerField(default=0, verbose_name='Общее количество бонусных товаров')),
                ('first_used', models.DateTimeField(blank=True, null=True, verbose_name='Первое использование')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='bonuses.bonusrule', verbose_name='Правило')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Использование правила бонусов',
                'verbose_name_plural': 'Использования правил бонусов',
                'db_table': 'bonus_rule_usage',
                'unique_together': {('rule', 'store')},
            },
        ),
    ]
