# Generated by Django 5.2.5 on 2025-09-16 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonuses', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusbalance',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_balance', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_history', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.category', verbose_name='Категории'),
        ),
    ]
