# Generated by Django 5.2.5 on 2025-09-16 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonuses', '0002_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Если не выбрано - применяется ко всем', to='products.product', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='bonusrule',
            name='stores',
            field=models.ManyToManyField(blank=True, to='stores.store', verbose_name='Магазины'),
        ),
        migrations.AddField(
            model_name='bonushistory',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonuses.bonusrule', verbose_name='Правило бонуса'),
        ),
        migrations.AddField(
            model_name='bonusruleusage',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='bonuses.bonusrule', verbose_name='Правило'),
        ),
        migrations.AddField(
            model_name='bonusruleusage',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterUniqueTogether(
            name='bonusruleusage',
            unique_together={('rule', 'store')},
        ),
    ]
