# Generated by Django 5.2.5 on 2025-09-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код региона')),
                ('region_type', models.CharField(choices=[('country', 'Страна'), ('oblast', 'Область'), ('district', 'Район'), ('city', 'Город'), ('village', 'Село')], default='city', max_length=20, verbose_name='Тип региона')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='regions.region', verbose_name='Родительский регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зоны')),
                ('polygon_coordinates', models.JSONField(blank=True, default=list, help_text='Координаты полигона зоны доставки в формате [[lat, lng], ...]', verbose_name='Координаты полигона')),
                ('delivery_radius', models.IntegerField(blank=True, help_text='Радиус доставки в метрах', null=True, verbose_name='Радиус доставки (м)')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость доставки')),
                ('delivery_time_hours', models.IntegerField(default=24, verbose_name='Время доставки (часы)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='regions.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Зона доставки',
                'verbose_name_plural': 'Зоны доставки',
                'db_table': 'delivery_zones',
                'ordering': ['region', 'name'],
            },
        ),
    ]
