# Generated by Django 5.2.5 on 2025-09-21 05:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='region',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='region',
            name='delivery_radius_km',
            field=models.PositiveIntegerField(default=20, verbose_name='Радиус доставки (км)'),
        ),
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='region',
            name='priority',
            field=models.PositiveIntegerField(default=5, verbose_name='Приоритет обслуживания (1-10)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название региона'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='region',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_type',
        ),
    ]
