# Generated by Django 5.2.5 on 2025-09-21 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'В процессе'), ('approved', 'Одобрен'), ('rejected', 'Отказано')], default='approved', max_length=10, verbose_name='Статус одобрения'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(max_length=5, verbose_name='5-значный код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Email должен содержать ровно один символ @ и быть корректным', regex='^[^@]+@[^@]+\\.[^@]+$')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен (не заблокирован)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +996XXXXXXXXX', regex='^\\+996\\d{9}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
