# Generated by Django 5.2.5 on 2025-08-30 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=22, max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я\\s]+$', 'ФИО должно содержать только буквы')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default=22, max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я\\s]+$', 'Фамилия должно содержать только буквы')]),
            preserve_default=False,
        ),
    ]
