# Generated by Django 5.2.5 on 2025-09-16 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cost_accounting', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_specs', to='products.product'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cost_accounting.billofmaterial'),
        ),
        migrations.AddField(
            model_name='dailyexpenselog',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='cost_accounting.expense'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_accounting.expense'),
        ),
        migrations.AddField(
            model_name='monthlyoverheadbudget',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost_accounting.expense'),
        ),
        migrations.AddField(
            model_name='productexpense',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='cost_accounting.expense'),
        ),
        migrations.AddField(
            model_name='productexpense',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_expenses', to='products.product'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyexpenselog',
            unique_together={('expense', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyoverheadbudget',
            unique_together={('year', 'month', 'expense')},
        ),
        migrations.AlterUniqueTogether(
            name='productexpense',
            unique_together={('product', 'expense')},
        ),
        migrations.AlterUniqueTogether(
            name='productionbatch',
            unique_together={('product', 'date')},
        ),
    ]
