# Generated by Django 5.2.5 on 2025-09-11 21:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininventory',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='admininventory',
            name='reserved_for_partners',
        ),
        migrations.CreateModel(
            name='MainInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество на главном складе')),
                ('reserved_for_partners', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Зарезервировано для партнёров')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_inventory', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Главный склад',
                'verbose_name_plural': 'Главный склад',
                'db_table': 'main_inventory',
            },
        ),
    ]
