# Generated by Django 5.2.5 on 2025-09-10 19:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_options_productimage_created_at_and_more'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeinventory',
            options={'ordering': ['store', 'product'], 'verbose_name': 'Остаток товара', 'verbose_name_plural': 'Остатки товаров'},
        ),
        migrations.AddField(
            model_name='storerequestitem',
            name='approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Одобренное количество'),
        ),
        migrations.AddField(
            model_name='storerequestitem',
            name='delivered_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Доставленное количество'),
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Зарезервировано'),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='storerequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='storerequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество'),
        ),
    ]
