# Generated by Django 5.2.5 on 2025-11-15 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='storerequest',
            name='store_reque_store_i_b6d370_idx',
        ),
        migrations.RemoveIndex(
            model_name='storerequest',
            name='store_reque_idempot_8435f4_idx',
        ),
        migrations.AlterField(
            model_name='storeselection',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'store'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_selections', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
