# Generated by Django 5.2.5 on 2025-10-12 20:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_remove_expense_partner_alter_product_unique_together_and_more'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая сумма возврата')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Запрос на возврат',
                'verbose_name_plural': 'Запросы на возврат',
                'db_table': 'return_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу')),
            ],
            options={
                'verbose_name': 'Позиция возврата',
                'verbose_name_plural': 'Позиции возвратов',
                'db_table': 'return_request_items',
            },
        ),
        migrations.AlterModelOptions(
            name='storeproductrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос товара', 'verbose_name_plural': 'Запросы товаров'},
        ),
        migrations.RemoveIndex(
            model_name='storerequest',
            name='store_reque_store_i_b6d370_idx',
        ),
        migrations.AlterUniqueTogether(
            name='storeproductrequest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='storerequestitem',
            name='total',
        ),
        migrations.AddField(
            model_name='store',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус одобрения'),
        ),
        migrations.AddField(
            model_name='storeproductrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='storerequestitem',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='store',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='storeproductrequest',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='storerequestitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='storerequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storeselection',
            name='selected_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выбора'),
        ),
        migrations.AlterField(
            model_name='storeselection',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='storeselection',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'store'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['inn', 'phone'], name='stores_inn_8807ec_idx'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.returnrequest', verbose_name='Запрос'),
        ),
        migrations.RemoveField(
            model_name='storeproductrequest',
            name='last_updated',
        ),
    ]
