# Generated by Django 5.2.5 on 2025-10-12 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_returnrequest_returnrequestitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
    ]
