# Generated by Django 5.2.5 on 2025-10-16 21:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_alter_bonushistory_options_and_more'),
        ('stores', '0003_returnrequest_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма долга')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Погашено')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Остаток')),
                ('status', models.CharField(choices=[('unpaid', 'Не погашен'), ('partially_paid', 'Частично погашен'), ('paid', 'Погашен')], default='unpaid', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата погашения')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'db_table': 'debts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('order', 'Полученные товары (заказ)'), ('bonus', 'Бонусы'), ('defective', 'Брак'), ('request', 'Запрошенные товары')], max_length=20, verbose_name='Тип действия')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Количество')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История магазина',
                'verbose_name_plural': 'История магазинов',
                'db_table': 'store_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='partnerinventory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='partnerinventory',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partnerinventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='order',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='store',
        ),
        migrations.RemoveField(
            model_name='returnrequestitem',
            name='request',
        ),
        migrations.RemoveField(
            model_name='returnrequestitem',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storeinventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storeinventory',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storeproductrequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storeproductrequest',
            name='store',
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-debt', '-created_at'], 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='storerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос товаров', 'verbose_name_plural': 'Запросы товаров'},
        ),
        migrations.AlterModelOptions(
            name='storerequestitem',
            options={'verbose_name': 'Товар в запросе', 'verbose_name_plural': 'Товары в запросе'},
        ),
        migrations.AlterModelOptions(
            name='storeselection',
            options={'ordering': ['-selected_at'], 'verbose_name': 'Выбор магазина', 'verbose_name_plural': 'Выборы магазинов'},
        ),
        migrations.RemoveIndex(
            model_name='store',
            name='stores_inn_8807ec_idx',
        ),
        migrations.RemoveField(
            model_name='region',
            name='code',
        ),
        migrations.RemoveField(
            model_name='store',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='store',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='store',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='storerequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='storerequest',
            name='note',
        ),
        migrations.RemoveField(
            model_name='storerequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='storerequest',
            name='total_amount',
        ),
        migrations.AlterUniqueTogether(
            name='storerequestitem',
            unique_together={('request', 'product')},
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('frozen', 'Заморожен')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_requests', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storerequestitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stores', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='store',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Долг'),
        ),
        migrations.AlterField(
            model_name='store',
            name='inn',
            field=models.CharField(max_length=14, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner_name',
            field=models.CharField(max_length=255, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storerequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storeselection',
            name='selected_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Выбран'),
        ),
        migrations.AlterField(
            model_name='storeselection',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='storeselection',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'store'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_selections', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='storeselection',
            unique_together={('user', 'store')},
        ),
        migrations.AddField(
            model_name='debt',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='debt',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_debts', to=settings.AUTH_USER_MODEL, verbose_name='Кто погасил'),
        ),
        migrations.AddField(
            model_name='debt',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_debts', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='debt',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='storehistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='storehistory',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_history', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='storehistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='storehistory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='storehistory',
            name='store_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storerequest', verbose_name='Запрос товаров'),
        ),
        migrations.DeleteModel(
            name='PartnerInventory',
        ),
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
        migrations.DeleteModel(
            name='ReturnRequestItem',
        ),
        migrations.DeleteModel(
            name='StoreInventory',
        ),
        migrations.DeleteModel(
            name='StoreProductRequest',
        ),
        migrations.RemoveField(
            model_name='storerequestitem',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='storerequestitem',
            name='price',
        ),
    ]
