# Generated by Django 5.2.5 on 2025-10-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_debt_storehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storehistory',
            name='remaining_debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Оставшийся долг'),
        ),
        migrations.AlterField(
            model_name='storehistory',
            name='action_type',
            field=models.CharField(choices=[('order', 'Полученные товары'), ('bonus', 'Бонусы'), ('defective', 'Бракованные товары'), ('debt', 'Долг (оставшийся)'), ('request', 'Запросы магазина')], max_length=20, verbose_name='Тип действия'),
        ),
    ]
