# Generated by Django 5.2.5 on 2025-10-31 09:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_idempotency_key'),
        ('products', '0004_alter_bonushistory_options_and_more'),
        ('stores', '0005_storehistory_remaining_debt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Инвентарь партнёра',
                'verbose_name_plural': 'Инвентарь партнёров',
                'db_table': 'partner_inventory',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая сумма возврата')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Запрос на возврат',
                'verbose_name_plural': 'Запросы на возврат',
                'db_table': 'return_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу')),
            ],
            options={
                'verbose_name': 'Позиция возврата',
                'verbose_name_plural': 'Позиции возвратов',
                'db_table': 'return_request_items',
            },
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Инвентарь магазина',
                'verbose_name_plural': 'Инвентарь магазинов',
                'db_table': 'store_inventory',
            },
        ),
        migrations.CreateModel(
            name='StoreProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Запрос товара',
                'verbose_name_plural': 'Запросы товаров',
                'db_table': 'store_product_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='debt',
            name='order',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storehistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='storehistory',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='storehistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storehistory',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storehistory',
            name='store_request',
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at'], 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='storerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос магазина', 'verbose_name_plural': 'Запросы магазинов'},
        ),
        migrations.AlterModelOptions(
            name='storerequestitem',
            options={'verbose_name': 'Позиция запроса', 'verbose_name_plural': 'Позиции запросов'},
        ),
        migrations.AlterModelOptions(
            name='storeselection',
            options={'verbose_name': 'Выбор магазина', 'verbose_name_plural': 'Выборы магазинов'},
        ),
        migrations.AlterUniqueTogether(
            name='storerequestitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='storeselection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='store',
            name='status',
        ),
        migrations.RemoveField(
            model_name='storerequest',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='storerequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='store',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус одобрения'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая сумма'),
        ),
        migrations.AddField(
            model_name='storerequestitem',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
        migrations.AddField(
            model_name='storerequestitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='store',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Долг'),
        ),
        migrations.AlterField(
            model_name='store',
            name='inn',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='ИНН должен быть 12-14 цифр', regex='^\\d{12,14}$')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner_name',
            field=models.CharField(max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Формат: +996XXXXXXXXX', regex='^\\+996\\d{9}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='storerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='storerequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storeselection',
            name='selected_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выбора'),
        ),
        migrations.AlterField(
            model_name='storeselection',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='storeselection',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'store'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['inn', 'phone'], name='stores_inn_8807ec_idx'),
        ),
        migrations.AddField(
            model_name='partnerinventory',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='partnerinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.returnrequest', verbose_name='Запрос'),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='storeproductrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='storeproductrequest',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.DeleteModel(
            name='StoreHistory',
        ),
        migrations.RemoveField(
            model_name='storerequestitem',
            name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='partnerinventory',
            unique_together={('partner', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together={('store', 'product')},
        ),
    ]
