# Generated by Django 5.2.5 on 2025-11-06 08:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_partnerorder_storeorder_storeorderitem_and_more'),
        ('products', '0005_productcategory_alter_bonushistory_options_and_more'),
        ('stores', '0006_partnerinventory_returnrequest_returnrequestitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='code',
        ),
        migrations.RemoveField(
            model_name='storerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AddField(
            model_name='storerequest',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.partnerorder', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='returnrequestitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='storeproductrequest',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Запрошенное количество'),
        ),
        migrations.AlterField(
            model_name='storerequestitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена за единицу'),
        ),
        migrations.AlterUniqueTogether(
            name='storeproductrequest',
            unique_together={('store', 'product')},
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['partner', 'created_at'], name='return_requ_partner_d35914_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['idempotency_key'], name='return_requ_idempot_174448_idx'),
        ),
        migrations.AddIndex(
            model_name='storerequest',
            index=models.Index(fields=['store', 'created_at'], name='store_reque_store_i_b6d370_idx'),
        ),
        migrations.AddIndex(
            model_name='storerequest',
            index=models.Index(fields=['idempotency_key'], name='store_reque_idempot_8435f4_idx'),
        ),
    ]
