# Generated by Django 5.2.5 on 2025-09-11 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('picked_up', 'Забран со склада'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('failed', 'Не доставлен'), ('returned', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Текущая широта')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Текущая долгота')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='Время забора')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Время доставки')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемая доставка')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Расстояние (км)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отслеживание доставки',
                'verbose_name_plural': 'Отслеживание доставок',
                'db_table': 'delivery_tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Скорость (км/ч)')),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tracking.deliverytracking', verbose_name='Отслеживание')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
                'db_table': 'tracking_points',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер')),
                ('vehicle_type', models.CharField(choices=[('car', 'Легковой автомобиль'), ('van', 'Фургон'), ('truck', 'Грузовик'), ('motorcycle', 'Мотоцикл')], max_length=20, verbose_name='Тип транспорта')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Модель')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('drivers', models.ManyToManyField(blank=True, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Водители')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
                'db_table': 'vehicles',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.vehicle', verbose_name='Транспорт'),
        ),
    ]
