# Generated by Django 5.2.5 on 2025-09-16 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytracking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='trackingpoint',
            name='tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tracking.deliverytracking', verbose_name='Отслеживание'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Водители'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.vehicle', verbose_name='Транспорт'),
        ),
    ]
