# Generated by Django 5.2.5 on 2025-11-11 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sales', 'Продажи'), ('debts', 'Долги'), ('costs', 'Расходы'), ('bonuses', 'Бонусы'), ('brak', 'Брак'), ('balance', 'Баланс'), ('orders', 'Заказы'), ('products', 'Товары'), ('markup', 'Наценка')], max_length=20, verbose_name='Тип отчёта')),
                ('data', models.JSONField(verbose_name='Данные отчёта')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdfs/', verbose_name='PDF файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сгенерировал')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
