# Generated by Django 5.2.5 on 2025-09-16 12:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('sold_quantity', models.PositiveIntegerField(default=0, verbose_name='Продано (ед.)')),
                ('bonus_quantity', models.PositiveIntegerField(default=0, verbose_name='Бесплатно выдано (ед.)')),
                ('bonus_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма бонусной скидки')),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Выручка с учётом бонусов')),
                ('bonus_rule_n', models.PositiveIntegerField(default=21, verbose_name='Правило бонусов (каждый N-й)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Отчет по бонусам (день)',
                'verbose_name_plural': 'Отчеты по бонусам (день)',
                'db_table': 'bonus_reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BonusReportMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_bonus_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма бонусных скидок за месяц')),
                ('total_bonus_items', models.PositiveIntegerField(default=0, verbose_name='Всего бесплатных единиц')),
                ('days_with_bonuses', models.PositiveIntegerField(default=0, verbose_name='Дней с бонусами')),
                ('avg_daily_bonus_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Средняя бонусная скидка в день')),
                ('avg_daily_bonus_items', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Среднее бесплатных единиц в день')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отчет по бонусам (месяц)',
                'verbose_name_plural': 'Отчеты по бонусам (месяц)',
                'db_table': 'bonus_reports_monthly',
            },
        ),
        migrations.CreateModel(
            name='CostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('materials_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Материалы (ингредиенты/упаковка)')),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Накладные расходы')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Себестоимость итого')),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Произведено (шт/кг)')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Метаданные (алгоритм, доли и пр.)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Отчет по себестоимости',
                'verbose_name_plural': 'Отчеты по себестоимости',
                'db_table': 'cost_reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DebtReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('opening_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Долг на начало')),
                ('new_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Начислено за период')),
                ('paid_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Погашено за период')),
                ('closing_debt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Долг на конец')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Отчет по долгам',
                'verbose_name_plural': 'Отчеты по долгам',
                'db_table': 'debt_reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('opening_balance', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Остаток на начало')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Поступило')),
                ('sold_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Продано')),
                ('closing_balance', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Остаток на конец')),
                ('opening_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Стоимость на начало')),
                ('closing_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Стоимость на конец')),
            ],
            options={
                'verbose_name': 'Отчет по остаткам',
                'verbose_name_plural': 'Отчеты по остаткам',
                'db_table': 'inventory_reports',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('report_type', models.CharField(choices=[('sales', 'Отчет по продажам'), ('inventory', 'Отчет по остаткам'), ('debts', 'Отчет по долгам'), ('bonuses', 'Отчет по бонусам'), ('costs', 'Отчет по себестоимости'), ('profit', 'Отчет по прибыли'), ('partner_performance', 'Отчет по партнерам'), ('store_performance', 'Отчет по магазинам')], max_length=32, verbose_name='Тип отчета')),
                ('period', models.CharField(choices=[('daily', 'За день'), ('weekly', 'За неделю'), ('monthly', 'За месяц'), ('quarterly', 'За квартал'), ('yearly', 'За год'), ('custom', 'Произвольный период')], max_length=20, verbose_name='Период')),
                ('date_from', models.DateField(verbose_name='Дата начала')),
                ('date_to', models.DateField(verbose_name='Дата окончания')),
                ('data', models.JSONField(default=dict, verbose_name='Данные отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_automated', models.BooleanField(default=False, verbose_name='Автоматический')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Количество заказов')),
                ('total_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Общее количество')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Выручка')),
                ('total_bonus_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Бонусные скидки')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Себестоимость')),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Прибыль')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Отчет по продажам',
                'verbose_name_plural': 'Отчеты по продажам',
                'db_table': 'sales_reports',
                'ordering': ['-date'],
            },
        ),
    ]
