# Generated by Django 5.2.5 on 2025-09-11 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('report_type', models.CharField(choices=[('sales', 'Отчет по продажам'), ('inventory', 'Отчет по остаткам'), ('debts', 'Отчет по долгам'), ('bonuses', 'Отчет по бонусам'), ('costs', 'Отчет по себестоимости'), ('profit', 'Отчет по прибыли'), ('partner_performance', 'Отчет по партнерам'), ('store_performance', 'Отчет по магазинам')], max_length=20, verbose_name='Тип отчета')),
                ('period', models.CharField(choices=[('daily', 'За день'), ('weekly', 'За неделю'), ('monthly', 'За месяц'), ('quarterly', 'За квартал'), ('yearly', 'За год'), ('custom', 'Произвольный период')], max_length=20, verbose_name='Период')),
                ('date_from', models.DateField(verbose_name='Дата начала')),
                ('date_to', models.DateField(verbose_name='Дата окончания')),
                ('data', models.JSONField(default=dict, verbose_name='Данные отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_automated', models.BooleanField(default=False, verbose_name='Автоматический')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('partner', models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('opening_balance', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Остаток на начало')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Поступило')),
                ('sold_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Продано')),
                ('closing_balance', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Остаток на конец')),
                ('opening_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость на начало')),
                ('closing_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость на конец')),
                ('partner', models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Отчет по остаткам',
                'verbose_name_plural': 'Отчеты по остаткам',
                'db_table': 'inventory_reports',
                'unique_together': {('date', 'store', 'partner', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Количество заказов')),
                ('total_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Общее количество')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка')),
                ('total_bonus_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бонусные скидки')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себестоимость')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прибыль')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Отчет по продажам',
                'verbose_name_plural': 'Отчеты по продажам',
                'db_table': 'sales_reports',
                'ordering': ['-date'],
                'unique_together': {('date', 'store', 'product')},
            },
        ),
    ]
