# Generated by Django 5.2.5 on 2025-11-17 20:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2025, 11, 17, 20, 15, 27, 433492, tzinfo=datetime.timezone.utc), verbose_name='Период с'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2025, 11, 17, 20, 15, 35, 801114, tzinfo=datetime.timezone.utc), verbose_name='Период по'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные отчёта'),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Кем сгенерирован'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='PDF файл'),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('sales', 'Продажи'), ('debts', 'Долги'), ('costs', 'Расходы'), ('bonuses', 'Бонусы'), ('defects', 'Брак'), ('balance', 'Баланс'), ('orders', 'Заказы'), ('products', 'Товары'), ('markup', 'Наценка')], max_length=32, verbose_name='Тип отчёта'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['type', 'date_from', 'date_to'], name='reports_type_0b2c71_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_created_c5f642_idx'),
        ),
    ]
