# Generated by Django 5.2.5 on 2025-09-16 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cost_accounting', '0002_initial'),
        ('products', '0002_initial'),
        ('reports', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusreport',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='bonusreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='bonusreport',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost_accounting.productionbatch', verbose_name='Производственная партия'),
        ),
        migrations.AddField(
            model_name='bonusreport',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='bonusreportmonthly',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='bonusreportmonthly',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='costreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='costreport',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost_accounting.productionbatch', verbose_name='Производственная партия'),
        ),
        migrations.AddField(
            model_name='debtreport',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='debtreport',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost_accounting.productionbatch', verbose_name='Производственная партия (для расчёта себестоимости)'),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='report',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='report',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='report',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddIndex(
            model_name='bonusreport',
            index=models.Index(fields=['date'], name='bonus_repor_date_686010_idx'),
        ),
        migrations.AddIndex(
            model_name='bonusreport',
            index=models.Index(fields=['partner'], name='bonus_repor_partner_7a5cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='bonusreport',
            index=models.Index(fields=['store'], name='bonus_repor_store_i_e73df3_idx'),
        ),
        migrations.AddIndex(
            model_name='bonusreport',
            index=models.Index(fields=['product'], name='bonus_repor_product_f1f35c_idx'),
        ),
        migrations.AddIndex(
            model_name='bonusreport',
            index=models.Index(fields=['production_batch'], name='bonus_repor_product_e39a78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bonusreport',
            unique_together={('date', 'partner', 'store', 'product')},
        ),
        migrations.AddIndex(
            model_name='bonusreportmonthly',
            index=models.Index(fields=['year', 'month'], name='bonus_repor_year_3a6ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='bonusreportmonthly',
            index=models.Index(fields=['partner'], name='bonus_repor_partner_24b546_idx'),
        ),
        migrations.AddIndex(
            model_name='bonusreportmonthly',
            index=models.Index(fields=['store'], name='bonus_repor_store_i_73ad2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bonusreportmonthly',
            unique_together={('year', 'month', 'partner', 'store')},
        ),
        migrations.AddIndex(
            model_name='costreport',
            index=models.Index(fields=['date'], name='cost_report_date_f5a5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='costreport',
            index=models.Index(fields=['product'], name='cost_report_product_ca05b2_idx'),
        ),
        migrations.AddIndex(
            model_name='costreport',
            index=models.Index(fields=['production_batch'], name='cost_report_product_fd5257_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costreport',
            unique_together={('date', 'product')},
        ),
        migrations.AddIndex(
            model_name='debtreport',
            index=models.Index(fields=['date'], name='debt_report_date_ccbba4_idx'),
        ),
        migrations.AddIndex(
            model_name='debtreport',
            index=models.Index(fields=['partner'], name='debt_report_partner_c546bc_idx'),
        ),
        migrations.AddIndex(
            model_name='debtreport',
            index=models.Index(fields=['store'], name='debt_report_store_i_fd53b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='debtreport',
            unique_together={('date', 'partner', 'store')},
        ),
        migrations.AddIndex(
            model_name='inventoryreport',
            index=models.Index(fields=['date'], name='inventory_r_date_0892cb_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreport',
            index=models.Index(fields=['store'], name='inventory_r_store_i_fa05ad_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreport',
            index=models.Index(fields=['partner'], name='inventory_r_partner_6d6156_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreport',
            index=models.Index(fields=['product'], name='inventory_r_product_d7fadc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreport',
            index=models.Index(fields=['production_batch'], name='inventory_r_product_3edf3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryreport',
            unique_together={('date', 'store', 'partner', 'product')},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'date_from', 'date_to'], name='reports_report__9bb278_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['store'], name='reports_store_i_46f1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['partner'], name='reports_partner_e7344a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['product'], name='reports_product_e1b587_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['date'], name='sales_repor_date_610f04_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['partner'], name='sales_repor_partner_9684c6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['store'], name='sales_repor_store_i_c9062e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['product'], name='sales_repor_product_d70dd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesreport',
            unique_together={('date', 'partner', 'store', 'product')},
        ),
    ]
