# Generated by Django 5.2.5 on 2025-09-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusreport',
            name='bonus_rule_n',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Правило бонусов (каждый N-й)'),
        ),
    ]
