# Generated by Django 5.2.5 on 2025-09-16 13:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('reports', '0003_alter_bonusreport_bonus_rule_n'),
        ('stores', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма списания')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Причина')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Брак (списание)',
                'verbose_name_plural': 'Брак (списания)',
                'db_table': 'waste_logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('waste_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Кол-во брака (шт/кг)')),
                ('waste_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма брака')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Отчёт по браку (день)',
                'verbose_name_plural': 'Отчёты по браку (день)',
                'db_table': 'waste_reports',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='bonusreport',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='bonusreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='bonusreport',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='bonusreportmonthly',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='bonusreportmonthly',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='costreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='debtreport',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='debtreport',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='inventoryreport',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='inventoryreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='inventoryreport',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='report',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='report',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sales', 'Отчет по продажам'), ('inventory', 'Отчет по остаткам'), ('debts', 'Отчет по долгам'), ('bonuses', 'Отчет по бонусам'), ('costs', 'Отчет по себестоимости'), ('profit', 'Отчет по прибыли'), ('partner_performance', 'Отчет по партнерам'), ('store_performance', 'Отчет по магазинам'), ('waste', 'Отчет по браку')], max_length=32, verbose_name='Тип отчета'),
        ),
        migrations.AlterField(
            model_name='report',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['date', 'store'], name='sales_repor_date_7a685e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['date', 'partner'], name='sales_repor_date_698eb7_idx'),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_waste_logs', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddIndex(
            model_name='wastelog',
            index=models.Index(fields=['date'], name='waste_logs_date_daca53_idx'),
        ),
        migrations.AddIndex(
            model_name='wastelog',
            index=models.Index(fields=['store'], name='waste_logs_store_i_20981c_idx'),
        ),
        migrations.AddIndex(
            model_name='wastelog',
            index=models.Index(fields=['partner'], name='waste_logs_partner_d322b1_idx'),
        ),
        migrations.AddIndex(
            model_name='wastelog',
            index=models.Index(fields=['product'], name='waste_logs_product_b52244_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['date'], name='waste_repor_date_c9f5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['partner'], name='waste_repor_partner_e0d231_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['store'], name='waste_repor_store_i_0a4746_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['product'], name='waste_repor_product_339959_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wastereport',
            unique_together={('date', 'partner', 'store', 'product')},
        ),
    ]
