# Generated by Django 5.2.5 on 2025-08-30 23:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма долга')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Погашен')),
                ('description', models.TextField(verbose_name='Описание долга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок погашения')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата погашения')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='orders.order', verbose_name='Заказ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'db_table': 'debts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма платежа')),
                ('payment_date', models.DateTimeField(verbose_name='Дата платежа')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.debt', verbose_name='Долг')),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'partner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'Платеж по долгу',
                'verbose_name_plural': 'Платежи по долгам',
                'db_table': 'debt_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='DebtSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общий долг')),
                ('paid_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Погашенный долг')),
                ('unpaid_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Непогашенный долг')),
                ('period_start', models.DateTimeField(verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(verbose_name='Конец периода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(limit_choices_to={'role': 'partner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Сводка по долгам',
                'verbose_name_plural': 'Сводки по долгам',
                'db_table': 'debt_summaries',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'partner', 'period_start', 'period_end')},
            },
        ),
    ]
