# Generated by Django 5.2.5 on 2025-09-16 12:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма долга')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Погашен')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Погашенная сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата погашения')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата погашения')),
                ('description', models.TextField(verbose_name='Описание долга')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'db_table': 'debts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма платежа')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('transfer', 'Банковский перевод'), ('mobile', 'Мобильный платёж'), ('other', 'Другое')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакции')),
            ],
            options={
                'verbose_name': 'Платёж по долгу',
                'verbose_name_plural': 'Платежи по долгам',
                'db_table': 'debt_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общий долг')),
                ('overdue_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Просроченный долг')),
                ('active_debts_count', models.PositiveIntegerField(default=0, verbose_name='Количество активных долгов')),
                ('overdue_debts_count', models.PositiveIntegerField(default=0, verbose_name='Количество просроченных долгов')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего платежа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сводка долгов',
                'verbose_name_plural': 'Сводки долгов',
                'db_table': 'debt_summaries',
            },
        ),
    ]
