# Generated by Django 5.2.5 on 2025-09-10 19:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0002_alter_storeinventory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма долга')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Погашен')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Погашенная сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата погашения')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата погашения')),
                ('description', models.TextField(verbose_name='Описание долга')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_records', to='orders.order', verbose_name='Заказ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'db_table': 'debts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма платежа')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('transfer', 'Банковский перевод'), ('mobile', 'Мобильный платёж'), ('other', 'Другое')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакции')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.debt', verbose_name='Долг')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'Платёж по долгу',
                'verbose_name_plural': 'Платежи по долгам',
                'db_table': 'debt_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общий долг')),
                ('overdue_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Просроченный долг')),
                ('active_debts_count', models.PositiveIntegerField(default=0, verbose_name='Количество активных долгов')),
                ('overdue_debts_count', models.PositiveIntegerField(default=0, verbose_name='Количество просроченных долгов')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего платежа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt_summary', to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Сводка долгов',
                'verbose_name_plural': 'Сводки долгов',
                'db_table': 'debt_summaries',
            },
        ),
    ]
