# Generated by Django 5.2.5 on 2025-09-16 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0002_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.debt', verbose_name='Долг'),
        ),
    ]
