# Generated by Django 5.2.5 on 2025-09-23 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=16)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='GeoPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.IntegerField(blank=True, null=True)),
                ('speed_mps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bearing_deg', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, max_length=32, null=True)),
                ('battery', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_mock', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pings', to='geo.geodevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='geo_geoping_user_id_dbcf39_idx'), models.Index(fields=['recorded_at'], name='geo_geoping_recorde_58b677_idx')],
            },
        ),
    ]
